#! yaml-language-server: $schema=https://json.schemastore.org/yamllint.json
---
extends: default

rules:
  line-length:
    max: 100
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
