# <https://recyclarr.dev/wiki/yaml/config-reference/basic/>

radarr:
  anime-radarr:
    base_url: !secret radarr_url
    api_key: !secret radarr_api_key

    include:
      - template: radarr-quality-definition-movie
      - template: radarr-quality-profile-anime
      - template: radarr-custom-formats-anime

    custom_formats:
      - trash_ids:
          - 064af5f084a0a24458cc8ecd3220f93f # Uncensored
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 0 # Adjust scoring as desired

      - trash_ids:
          - a5d148168c4506b55cf53984107c396e # 10bit
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 0 # Adjust scoring as desired

      - trash_ids:
          - 4a3b087eea2ce012fcc1ce319259a3be # Anime Dual Audio
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 0 # Adjust scoring as desired
