include:
  - local-config.yaml

plugins:
  - chroma
  - convert
  - discogs
  - edit
  - embedart
  - fetchart
  - importadded
  - info
  - inline
  - lastgenre
  - plexupdate
  - replaygain

threaded: true

convert:
  auto: false
  ffmpeg: /usr/bin/ffmpeg
  opts: -ab 320k -ac 2 -ar 48000
  max_bitrate: 320
  threads: 1

paths:
  default: $albumartist/$album%aunique{}/%if{$multidisc,Disc $disc/}$track - $title
  comp: $albumartist/$album%aunique{}/%if{$multidisc,Disc $disc/}$track - $title

# Support for Plex
# https://forums.plex.tv/t/music-which-version-of-id3-tags-does-the-plex-scanner-inspect/193379/7
id3v23: true

item_fields:
  multidisc: 1 if disctotal > 1 else 0
  artist_differs: 1 if albumartist != artist else 0

import:
  bell: true
  copy: false
  # Doesn't allow upgrades.
  # incremental: true
  languages:
    - en
  log: ~/.config/beets/beet.log
  move: true
  quiet_fallback: skip
  timid: false
  write: true

match:
  preferred:
    countries: ["US", "UK|GB", "DE", "NL", "SE"]
    media: ["Digital Media|File", "CD"]
  strong_rec_thresh: 0.15
  medium_red_thresh: 0.25
  rec_gap_thresh: 0.25

musicbrainz:
  extra_tags: [year, catalognum, country, media, label]

# Use the album's original date instead of the release's date
original_date: yes

# Play it safe with filenames
asciify_paths: yes
max_filename_length: 255

ui:
  color: yes
  colors:
    text_success: green
    text_warning: yellow
    text_error: red
    text_highlight: red
    text_highlight_minor: lightgray
    action_default: turquoise
    action: blue

# Edit plugin
# https://beets.readthedocs.io/en/stable/plugins/edit.html
edit:
  itemfields: track title artist album
  albumfields: album albumartist

# FetchArt plugin
# https://beets.readthedocs.io/en/stable/plugins/fetchart.html
fetchart:
  sources: filesystem coverart discogs amazon albumart
  # enforce_ratio: 10px
  # minwidth: 300
  # maxwidth: 2000

# LastGenre plugin
# https://beets.readthedocs.io/en/stable/plugins/lastgenre.html
lastgenre:
  auto: true
  canonical: ~/.config/beets/canonical.yaml
  count: 4
  fallback: ""
  force: yes
  min_weight: 6
  prefer_specific: false
  separator: "; "
  source: album
  whitelist: ~/.config/beets/allowlist.txt

# ReplayGain plugin
# https://beets.readthedocs.io/en/stable/plugins/replaygain.html
replaygain:
  auto: yes
  backend: command

replace:
  '^\.': _
  '[\x00-\x1f]': _
  '[<>:"\?\*\|]': _
  '[\xE8-\xEB]': e
  '[\xEC-\xEF]': i
  '[\xE2-\xE6]': a
  '[\xF2-\xF6]': o
  '[\xF8]': o
  '\.$': _
  '\s+$': ""
